Update README.md
ripienaar/free-for-dev pull request #1709
Opened 2020-11-21 03:06 UTC by scalecampaign

added csv2geo tool api

2020-11-23 08:52 UTC, ripienaar requested changes

2020-11-23 08:52 UTC, ripienaar commented on README.md
> +  * [CSV2GEO](https://csv2geo.com) — Creates a batch geocoding API endpoint with interactive map. Supports normal and reverse geocoding with rooftop results.  Coverage is worldwide and it provides da
Can you please link to the free information? Nothing on their pricing page, only free thing is the input box on their front page which wouldn't really qualify for this list.

2020-11-24 04:20 UTC, Dean-ZhenYao-Wang commented
建议CMS部分增加Orchrd

2021-03-12 06:29 UTC, thispsj commented
> Can you please link to the free information? Nothing on their pricing page, only free thing is the input box on their front page which wouldn't really qualify for this list.

@ripienaar yes the only free thing is that input box on the home page. There's no free plan.
Please close this PR.

2021-03-12 06:31 UTC, closed without merging