Link Clean Up
ripienaar/free-for-dev pull request #2491
Opened 2022-07-01 22:09 UTC by KieranRobson

Cleaned up and updated URLs
There are plenty more but as this is my first PR - left it at these 5!

2022-07-02 10:07 UTC, ripienaar requested changes
small changes, thanks for this!

2022-07-02 10:07 UTC, ripienaar commented on README.md
> -  * [Hookbin](https://hookbin.com/) - Create unique (public or private) endpoints to collect, parse, and inspect HTTP requests. Inspect headers, body, query strings, cookies, uploaded files, etc. Use
this is still up and working

2022-07-02 10:07 UTC, ripienaar commented on README.md
> +  * [ScrapingBee](https://www.scrapingbee.com//) — Handle JS rendering, Chrome Headless, Proxy rotation and CAPTCHAs solving all in one place. The first 1000 are free of charge, no credit card requir
Its not clear now if this is 1000 free or 1000 free a month. So I am inclined to just remove it.

2022-07-02 15:09 UTC, merged

2022-07-02 15:09 UTC, ripienaar commented
thank you

2022-07-21 03:20 UTC, imba-tjd commented
I singed up ScrapingBee. It offers a one-time 1000 credits expired in 14 days. A simplest request consumes 5 points. Rendering JS consumes more.

2022-07-21 07:06 UTC, ripienaar commented
> I singed up ScrapingBee. It offers a one-time 1000 credits expired in 14 days. A simplest request consumes 5 points. Rendering JS consumes more.

Please send a PR to remove it

2022-07-21 07:27 UTC, imba-tjd commented
No need 😂 It's actually removed in this PR. I just share some info.